version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: business_management
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: business_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/sql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/sql/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mysql-volume:
